### ISSUE TITLE
E 3 error message?

### ISSUE THREAD

**Issue by thestumbler** [andysworkshop/awreflow2#2]
I'm testing one of these as you mentioned, by directly injecting 6.3V DC without mains connected.  It seems to be working, except I'm getting a flashing "E 3" on the LCD intermittently.  After a brief scan through the code, I can't see right off what generates E3.
-Chris

**Comment by andysworkshop** [comment]
The relevant source [is here](https://github.com/andysworkshop/awreflow2/blob/master/atmega8l/TemperatureDisplay.h#L71). It means an "OC fault" (open circuit) from the temperature sensor. See the table on page 10 of [the datasheet](https://datasheets.maximintegrated.com/en/ds/MAX31855.pdf).

**Comment by thestumbler** [comment]
Thanks, Andy.  That did the trick.  All's working fine now.
-Chris
